/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Record = IDL.Record({
  'id' : IDL.Nat,
  'sourceLang' : IDL.Text,
  'sourceText' : IDL.Text,
  'translatedText' : IDL.Text,
  'targetLang' : IDL.Text,
  'timestampNanos' : IDL.Int,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'deleteRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllHistory' : IDL.Func([], [IDL.Vec(Record)], ['query']),
  'saveTranslation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Record = IDL.Record({
    'id' : IDL.Nat,
    'sourceLang' : IDL.Text,
    'sourceText' : IDL.Text,
    'translatedText' : IDL.Text,
    'targetLang' : IDL.Text,
    'timestampNanos' : IDL.Int,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'deleteRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllHistory' : IDL.Func([], [IDL.Vec(Record)], ['query']),
    'saveTranslation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };